export default function PrivacyPage() {
  return <main className="min-h-screen bg-page px-6 py-12 text-ink"><article className="mx-auto max-w-3xl card p-8">
    <h1 className="text-3xl font-black">Privacy Policy</h1>
    <p className="mt-2 text-sm text-faint">Effective October 2, 2026</p>
    <div className="mt-8 space-y-6 text-sm leading-7 text-muted">
      <section><h2 className="text-lg font-bold text-ink">Who we are</h2><p>Owed is operated by Storm And Me LLC. Owed helps businesses manage overdue invoices and send payment reminders by email and, where enabled, SMS.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Information we collect</h2><p>We process account details such as your name, business name, email address, authentication data, settings, and subscription status. To provide the service, we also process customer and invoice information you upload or enter, including names, email addresses, phone numbers, invoice numbers, balances, due dates, reminder preferences, consent records, and message activity.</p></section>
      <section><h2 className="text-lg font-bold text-ink">How we use information</h2><p>We use information to provide and secure Owed, authenticate accounts, import and manage invoices, generate and deliver reminders, process replies and opt-outs, maintain audit history, provide billing, prevent abuse, troubleshoot problems, and improve reliability. We do not sell personal information.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Service providers</h2><p>Owed uses infrastructure and service providers to operate the product, including hosting/database providers, Resend for email delivery, an SMS carrier when SMS is enabled, Stripe for subscription billing, and OpenAI for optional AI-assisted reminder drafting. Providers process information only as needed to deliver their services and are subject to their own terms and privacy practices.</p></section>
      <section><h2 className="text-lg font-bold text-ink">SMS and consent</h2><p>Businesses using Owed are responsible for having the rights and consent required to contact their customers. Owed records SMS consent and opt-out state and blocks SMS after recognized opt-out requests. Consent to receive SMS is not a condition of purchasing Owed.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Retention and security</h2><p>We retain information for as long as reasonably necessary to provide the service, satisfy legal or accounting obligations, resolve disputes, and enforce agreements. We use technical and organizational safeguards including encrypted transport, restricted server-side credentials, authenticated sessions, request validation, provider webhook verification, and tenant-scoped data access.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Your choices</h2><p>Account owners may update account information and invoice/customer records in Owed. Customers receiving reminders may opt out of SMS using supported opt-out keywords. Requests concerning access, correction, deletion, or privacy questions can be sent to hello@stormandmeofficial.com.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Changes</h2><p>We may update this policy as the service changes. Material updates will be reflected by changing the effective date on this page.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Contact</h2><p>Storm And Me LLC<br/>Email: hello@stormandmeofficial.com</p></section>
    </div>
  </article></main>;
}
