import Link from "next/link";
import { getCurrentUser } from "../lib/auth/session";

export default async function Home() {
  const user = await getCurrentUser();
  return <main className="min-h-screen">
    <header className="border-b border-hairline"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><div><p className="text-2xl font-bold tracking-tight">Owed</p><p className="text-xs text-faint">Get paid what’s owed.</p></div><div className="flex gap-2">{user?<Link href="/dashboard" className="btn-primary">Open dashboard</Link>:<><Link href="/login" className="btn-secondary">Sign in</Link><Link href="/signup" className="btn-primary">Start free</Link></>}</div></div></header>
    <section className="mx-auto max-w-6xl px-5 pb-16 pt-20 sm:px-8 sm:pt-28"><div className="max-w-3xl"><span className="rounded-full border border-amber/30 bg-amber-dim px-3 py-1 text-xs font-semibold text-amber">Invoice follow-up without the awkward chase</span><h1 className="mt-6 text-5xl font-bold tracking-tight sm:text-7xl">You did the work.<br/><span className="text-amber">Owed gets you paid.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted">Automated email and SMS reminders for trades and service businesses. Friendly first, firmer when needed, and every serious escalation waits for your approval.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="btn-primary px-6 py-3">Start collecting</Link><a href="#how" className="btn-secondary px-6 py-3">See how it works</a></div></div>
      <div id="how" className="mt-24 grid gap-4 md:grid-cols-3">{[["1","Import invoices","Upload a simple CSV. No accounting login required to get started."],["2","Owed follows up","A six-stage cadence moves from polite email to direct SMS, while respecting quiet hours and customer preferences."],["3","You stay in control","Replies pause the chase automatically. Firm messages wait for your approval, edit, or snooze."]].map(([n,t,d])=><article key={n} className="card p-6"><span className="font-mono text-amber">0{n}</span><h2 className="mt-4 text-xl font-bold">{t}</h2><p className="mt-2 text-sm leading-relaxed text-muted">{d}</p></article>)}</div>
      <section className="mt-24"><div className="flex items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[.18em] text-amber">Pricing</p><h2 className="mt-2 text-3xl font-bold">Cheap compared with one forgotten invoice.</h2></div></div><div className="mt-8 grid gap-4 md:grid-cols-2"><article className="card p-7"><h3 className="text-xl font-bold">Starter</h3><p className="mt-2 text-4xl font-bold">$29<span className="text-base font-normal text-muted">/mo</span></p><p className="mt-4 text-sm text-muted">Email reminders, approval queue, CSV imports, reply pause, tone controls.</p></article><article className="rounded-lg border border-amber/40 bg-surface p-7"><h3 className="text-xl font-bold">Pro</h3><p className="mt-2 text-4xl font-bold">$39<span className="text-base font-normal text-muted">/mo</span></p><p className="mt-4 text-sm text-muted">Everything in Starter plus SMS escalation and AI-assisted tone-aware drafts.</p></article></div></section>
    </section>
    <footer className="border-t border-hairline"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-8 text-xs text-faint sm:px-8"><p>© 2026 Owed. Built for businesses that already earned the money.</p><div className="flex gap-4"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></footer>
  </main>;
}
