"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export default function IntegrationStatus({ email, sms, ai, billing, sendMode, businessName, timezone }:{ email:boolean; sms:boolean; ai:boolean; billing:boolean; sendMode:string; businessName:string; timezone:string }){
  const router=useRouter(); const [name,setName]=useState(businessName); const [tz,setTz]=useState(timezone); const [msg,setMsg]=useState("");
  async function save(){setMsg("Saving…");const r=await fetch('/api/account',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessName:name,timezone:tz})});const d=await r.json().catch(()=>({}));setMsg(r.ok?'Saved.':d.error||'Could not save.');if(r.ok)router.refresh();}
  const items=[['Email',email],['SMS',sms],['AI drafts',ai],['Billing',billing]] as const;
  return <section className="card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Launch controls</h2><p className="mt-1 text-sm text-faint">Provider readiness and account timezone.</p></div><span className={`rounded-full px-2.5 py-1 text-xs ${sendMode==='live'?'bg-success/15 text-success':'bg-amber-dim text-amber'}`}>{sendMode==='live'?'Live':'Simulation'}</span></div><div className="mt-4 grid grid-cols-2 gap-2">{items.map(([label,on])=><div key={label} className="rounded-md bg-surface2 px-3 py-2 text-xs"><span className={on?'text-success':'text-faint'}>{on?'●':'○'}</span> <span className="text-muted">{label}</span></div>)}</div><label className="mt-4 block text-xs text-muted">Business name<input className="field mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><label className="mt-3 block text-xs text-muted">IANA timezone<input className="field mt-1" value={tz} onChange={e=>setTz(e.target.value)} placeholder="America/New_York"/></label><div className="mt-3 flex items-center gap-3"><button onClick={save} className="btn-secondary">Save settings</button>{msg&&<span className="text-xs text-faint">{msg}</span>}</div></section>
}
