"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { formatMoney } from "../lib/format";
export interface InvoiceItem { id:string; number:string; customerName:string; amountCents:number; dueDate:string; daysOverdue:number; status:"open"|"reminded"|"escalated"|"paused"|"paid"|"disputed"; }
const styles:Record<InvoiceItem["status"],string>={open:"bg-surface2 text-muted",reminded:"bg-amber-dim text-amber",escalated:"bg-danger/15 text-danger",paused:"bg-surface2 text-amber",paid:"bg-success/15 text-success",disputed:"bg-surface2 text-faint"};
export default function InvoiceList({ invoices }:{invoices:InvoiceItem[]}) { const router=useRouter(); const [busy,setBusy]=useState<string|null>(null); async function setStatus(id:string,status:string){setBusy(id);const r=await fetch(`/api/invoices/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});setBusy(null);if(r.ok)router.refresh();}
  return <section><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Invoices</h2><span className="text-xs text-faint">{invoices.length} total</span></div><div className="mt-4 overflow-x-auto rounded-lg border border-hairline bg-surface"><table className="w-full min-w-[780px] text-left text-sm"><thead><tr className="border-b border-hairline text-[11px] uppercase tracking-widest text-faint"><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Due</th><th className="px-5 py-3 text-right">Amount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-hairline">{invoices.map(i=><tr key={i.id}><td className="px-5 py-3.5 font-mono">{i.number}</td><td className="px-5 py-3.5 text-muted">{i.customerName}</td><td className="px-5 py-3.5 font-mono text-faint">{i.dueDate}</td><td className="px-5 py-3.5 text-right font-semibold tnum">{formatMoney(i.amountCents)}</td><td className="px-5 py-3.5"><span className={`rounded-full px-2.5 py-1 text-xs ${styles[i.status]}`}>{i.status==="open"&&i.daysOverdue>0?`${i.daysOverdue}d overdue`:i.status}</span></td><td className="px-5 py-3.5 text-right"><select disabled={busy===i.id} value={i.status==="reminded"||i.status==="escalated"?"open":i.status} onChange={e=>setStatus(i.id,e.target.value)} className="rounded border border-hairline bg-surface2 px-2 py-1 text-xs"><option value="open">Active</option><option value="paused">Paused</option><option value="paid">Paid</option><option value="disputed">Disputed</option></select></td></tr>)}</tbody></table></div></section>;
}
