export default function TermsPage() {
  return <main className="min-h-screen bg-page px-6 py-12 text-ink"><article className="mx-auto max-w-3xl card p-8">
    <h1 className="text-3xl font-black">Terms of Service</h1>
    <p className="mt-2 text-sm text-faint">Effective October 2, 2026</p>
    <div className="mt-8 space-y-6 text-sm leading-7 text-muted">
      <section><h2 className="text-lg font-bold text-ink">Agreement</h2><p>These Terms govern access to and use of Owed, a service operated by Storm And Me LLC. By creating an account or using Owed, you agree to these Terms.</p></section>
      <section><h2 className="text-lg font-bold text-ink">The service</h2><p>Owed helps businesses organize invoices and automate payment follow-up. Owed is not a law firm, collection agency, credit bureau, payment processor, or accounting firm, and it does not provide legal, tax, accounting, or financial advice.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Your responsibilities</h2><p>You are responsible for the accuracy and legality of the data you provide, the invoices you pursue, the messages you approve or send, and your compliance with applicable laws, contracts, privacy rules, telemarketing and messaging rules. You must have authority to upload customer data and to contact each recipient through the selected channel.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Messaging rules</h2><p>You may not use Owed to send deceptive, abusive, threatening, unlawful, or unsolicited messages. You must honor opt-out requests. Owed may pause or restrict messaging when required to protect recipients, providers, or the service.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Subscriptions and billing</h2><p>Paid plans renew on the billing interval shown at checkout until canceled. Stripe processes subscription payments. Plan changes, cancellations, refunds, taxes, and billing details are handled according to the checkout and customer portal terms shown at the time of purchase and applicable law.</p></section>
      <section><h2 className="text-lg font-bold text-ink">AI-assisted drafting</h2><p>AI-assisted drafts are suggestions. You remain responsible for reviewing the content you send. Owed is designed to avoid invented fees, legal threats, or service-cutoff claims, but automated output may still contain mistakes and should be reviewed where appropriate.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Availability</h2><p>We work to keep Owed available and reliable, but no online service is uninterrupted. Delivery can also depend on third-party email, SMS, payment, hosting, and network providers. We may change or discontinue features where reasonably necessary.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Acceptable use and suspension</h2><p>We may suspend or terminate access for fraud, abuse, security threats, unlawful conduct, nonpayment, or material violation of these Terms. You may stop using Owed and cancel a paid subscription through the available billing controls.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Disclaimers and liability</h2><p>Owed is provided on an “as is” and “as available” basis to the extent permitted by law. Storm And Me LLC disclaims implied warranties to the extent permitted by law. To the maximum extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages, or for losses caused by customer-provided data, recipient disputes, or third-party services.</p></section>
      <section><h2 className="text-lg font-bold text-ink">Contact</h2><p>Questions about these Terms may be sent to hello@stormandmeofficial.com.</p></section>
    </div>
  </article></main>;
}
